In [43]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("Automobile_data.csv")

In [5]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450

In [155]:
df.head(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.4,7.0,160,5500,16,22,?

In [9]:
df.tail()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [10]:
df.tail(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
195,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,13415
196,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985
197,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,16515
198,-2,103,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18420
199,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18950
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [6]:
df['make']

0      alfa-romero
1      alfa-romero
2      alfa-romero
3             audi
4             audi
5             audi
6             audi
7             audi
8             audi
9             audi
10             bmw
11             bmw
12             bmw
13             bmw
14             bmw
15             bmw
16             bmw
17             bmw
18       chevrolet
19       chevrolet
20       chevrolet
21           dodge
22           dodge
23           dodge
24           dodge
25           dodge
26           dodge
27           dodge
28           dodge
29           dodge
          ...
175         toyota
176         toyota
177         toyota
178         toyota
179         toyota
180         toyota
181         toyota
182     volkswagen
183     volkswagen
184     volkswagen
185     volkswagen
186     volkswagen
187     volkswagen
188     volkswagen
189     volkswagen
190     volkswagen
191     volkswagen
192     volkswagen
193     volkswagen
194          volvo
195          volvo
196          volvo
197          volvo
198          volvo
199          volvo
200          volvo
201          volvo
202          volvo
203          volvo
204          volvo
Name: make, Length: 205, dtype: object

In [7]:
type(df['make'])

pandas.core.series.Series

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
symboling            205 non-null int64
normalized-losses    205 non-null object
make                 205 non-null object
fuel-type            205 non-null object
aspiration           205 non-null object
num-of-doors         205 non-null object
body-style           205 non-null object
drive-wheels         205 non-null object
engine-location      205 non-null object
wheel-base           205 non-null float64
length               205 non-null float64
width                205 non-null float64
height               205 non-null float64
curb-weight          205 non-null int64
engine-type          205 non-null object
num-of-cylinders     205 non-null object
engine-size          205 non-null int64
fuel-system          205 non-null object
bore                 205 non-null object
stroke               205 non-null object
compression-ratio    205 non-null float64
horsepower           205 non-null object
peak-rpm             205 non-null object
city-mpg             205 non-null int64
highway-mpg          205 non-null int64
price                205 non-null object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.7+ KB

In [13]:
df.describe()

,symboling,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

In [33]:
max(df.symboling.values)                     #.values convert into np array

3

In [18]:
max(df['wheel-base'].values)

120.9

In [19]:
df.symboling

0      3
1      3
2      1
3      2
4      2
5      2
6      1
7      1
8      1
9      0
10     2
11     0
12     0
13     0
14     1
15     0
16     0
17     0
18     2
19     1
20     0
21     1
22     1
23     1
24     1
25     1
26     1
27     1
28    -1
29     3
      ..
175   -1
176   -1
177   -1
178    3
179    3
180   -1
181   -1
182    2
183    2
184    2
185    2
186    2
187    2
188    2
189    3
190    3
191    0
192    0
193    0
194   -2
195   -1
196   -2
197   -1
198   -2
199   -1
200   -1
201   -1
202   -1
203   -1
204   -1
Name: symboling, Length: 205, dtype: int64

In [20]:
df.symboling.values

array([ 3,  3,  1,  2,  2,  2,  1,  1,  1,  0,  2,  0,  0,  0,  1,  0,  0,
        0,  2,  1,  0,  1,  1,  1,  1,  1,  1,  1, -1,  3,  2,  2,  1,  1,
        1,  0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0,  2,  0,  0,  0,  1,
        1,  1,  1,  1,  3,  3,  3,  3,  1,  0,  1,  0,  0,  0,  0,  0, -1,
       -1,  0, -1, -1,  3,  0,  1,  1,  2,  2,  2,  1,  3,  3,  3,  3,  3,
        1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  0,  0,  0,
        0,  0,  3,  3,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
        1,  1,  1,  1, -1,  3,  3,  3,  3,  3,  1,  0,  2,  3,  2,  3,  2,
        3,  2,  2,  2,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  2,  2,  2,
        2,  2,  2, -1, -1, -1, -1, -1,  3,  3, -1, -1,  2,  2,  2,  2,  2,
        2,  2,  3,  3,  0,  0,  0, -2, -1, -2, -1, -2, -1, -1, -1, -1, -1,
       -1], dtype=int64)

In [21]:
df['wheel-base']

0       88.6
1       88.6
2       94.5
3       99.8
4       99.4
5       99.8
6      105.8
7      105.8
8      105.8
9       99.5
10     101.2
11     101.2
12     101.2
13     101.2
14     103.5
15     103.5
16     103.5
17     110.0
18      88.4
19      94.5
20      94.5
21      93.7
22      93.7
23      93.7
24      93.7
25      93.7
26      93.7
27      93.7
28     103.3
29      95.9
       ...
175    102.4
176    102.4
177    102.4
178    102.9
179    102.9
180    104.5
181    104.5
182     97.3
183     97.3
184     97.3
185     97.3
186     97.3
187     97.3
188     97.3
189     94.5
190     94.5
191    100.4
192    100.4
193    100.4
194    104.3
195    104.3
196    104.3
197    104.3
198    104.3
199    104.3
200    109.1
201    109.1
202    109.1
203    109.1
204    109.1
Name: wheel-base, Length: 205, dtype: float64

In [22]:
df['wheel-base'].values

array([ 88.6,  88.6,  94.5,  99.8,  99.4,  99.8, 105.8, 105.8, 105.8,
        99.5, 101.2, 101.2, 101.2, 101.2, 103.5, 103.5, 103.5, 110. ,
        88.4,  94.5,  94.5,  93.7,  93.7,  93.7,  93.7,  93.7,  93.7,
        93.7, 103.3,  95.9,  86.6,  86.6,  93.7,  93.7,  93.7,  96.5,
        96.5,  96.5,  96.5,  96.5,  96.5,  96.5,  96.5,  94.3,  94.5,
        94.5,  96. , 113. , 113. , 102. ,  93.1,  93.1,  93.1,  93.1,
        93.1,  95.3,  95.3,  95.3,  95.3,  98.8,  98.8,  98.8,  98.8,
        98.8,  98.8, 104.9, 104.9, 110. , 110. , 106.7, 115.6, 115.6,
        96.6, 120.9, 112. , 102.7,  93.7,  93.7,  93.7,  93. ,  96.3,
        96.3,  95.9,  95.9,  95.9,  96.3,  96.3,  96.3,  96.3,  94.5,
        94.5,  94.5,  94.5,  94.5,  94.5,  94.5,  94.5,  94.5,  95.1,
        97.2,  97.2, 100.4, 100.4, 100.4,  91.3,  91.3,  99.2, 107.9,
       107.9, 114.2, 114.2, 107.9, 107.9, 114.2, 114.2, 107.9, 107.9,
       108. ,  93.7,  93.7,  93.7,  93.7,  93.7, 103.3,  95.9,  94.5,
        89.5,  89.5,  89.5,  98.4,  96.1,  96.1,  99.1,  99.1,  99.1,
        99.1,  99.1,  99.1,  93.7,  93.7,  93.3,  97.2,  97.2,  97.2,
        97. ,  97. ,  97. ,  97. ,  96.9,  96.9,  95.7,  95.7,  95.7,
        95.7,  95.7,  95.7,  95.7,  95.7,  95.7,  95.7,  95.7,  95.7,
        95.7,  94.5,  94.5,  94.5,  94.5,  98.4,  98.4,  98.4,  98.4,
        98.4,  98.4, 102.4, 102.4, 102.4, 102.4, 102.4, 102.9, 102.9,
       104.5, 104.5,  97.3,  97.3,  97.3,  97.3,  97.3,  97.3,  97.3,
        94.5,  94.5, 100.4, 100.4, 100.4, 104.3, 104.3, 104.3, 104.3,
       104.3, 104.3, 109.1, 109.1, 109.1, 109.1, 109.1])

In [25]:
df['curb-weight'].values.mean()

2555.5658536585365

In [26]:
df['curb-weight'].values.max()

4066

In [32]:
df['curb-weight'][:10]              #print first n data info

0    2548
1    2548
2    2823
3    2337
4    2824
5    2507
6    2844
7    2954
8    3086
9    3053
Name: curb-weight, dtype: int64

In [31]:
df['curb-weight'][::10]                  #10 is the stepsize

0      2548
10     2395
20     1909
30     1713
40     2372
50     1890
60     2410
70     3770
80     2370
90     2017
100    2302
110    3430
120    1967
130    2579
140    2240
150    1985
160    2094
170    2679
180    3131
190    2221
200    2952
Name: curb-weight, dtype: int64

In [34]:
df.loc[1:10]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.4,7.0,160,5500,16,22,?
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.5,2.8,8.8,101,5800,23,29,16430

In [36]:
df.iloc[1:10,0:2]

   symboling normalized-losses
1          3                 ?
2          1                 ?
3          2               164
4          2               164
5          2                 ?
6          1               158
7          1                 ?
8          1               158
9          0                 ?

In [39]:
df.iloc[1:10,[3,4,6]]

  fuel-type aspiration   body-style
1       gas        std  convertible
2       gas        std    hatchback
3       gas        std        sedan
4       gas        std        sedan
5       gas        std        sedan
6       gas        std        sedan
7       gas        std        wagon
8       gas      turbo        sedan
9       gas      turbo    hatchback

In [40]:
df.loc[[1,2,78],['make','aspiration']]

           make aspiration
1   alfa-romero        std
2   alfa-romero        std
78   mitsubishi        std

In [42]:
df.loc[:10,'make':'aspiration']

           make fuel-type aspiration
0   alfa-romero       gas        std
1   alfa-romero       gas        std
2   alfa-romero       gas        std
3          audi       gas        std
4          audi       gas        std
5          audi       gas        std
6          audi       gas        std
7          audi       gas        std
8          audi       gas      turbo
9          audi       gas      turbo
10          bmw       gas        std

In [52]:
a=np.arange(1,10)
b=np.arange(1,10)**2

In [53]:
pd.DataFrame({'number':a,'power':b})

   number  power
0       1      1
1       2      4
2       3      9
3       4     16
4       5     25
5       6     36
6       7     49
7       8     64
8       9     81

In [72]:
angle=np.arange(0,361)
sin=np.sin(angle * np.pi / 180. )
cos=np.cos(angle * np.pi / 180. )
tan=np.tan(angle * np.pi / 180. )

pd.DataFrame({'sine':sin,'cosine':cos,'tan':tan})

             sine    cosine           tan
0    0.000000e+00  1.000000  0.000000e+00
1    1.745241e-02  0.999848  1.745506e-02
2    3.489950e-02  0.999391  3.492077e-02
3    5.233596e-02  0.998630  5.240778e-02
4    6.975647e-02  0.997564  6.992681e-02
5    8.715574e-02  0.996195  8.748866e-02
6    1.045285e-01  0.994522  1.051042e-01
7    1.218693e-01  0.992546  1.227846e-01
8    1.391731e-01  0.990268  1.405408e-01
9    1.564345e-01  0.987688  1.583844e-01
10   1.736482e-01  0.984808  1.763270e-01
11   1.908090e-01  0.981627  1.943803e-01
12   2.079117e-01  0.978148  2.125566e-01
13   2.249511e-01  0.974370  2.308682e-01
14   2.419219e-01  0.970296  2.493280e-01
15   2.588190e-01  0.965926  2.679492e-01
16   2.756374e-01  0.961262  2.867454e-01
17   2.923717e-01  0.956305  3.057307e-01
18   3.090170e-01  0.951057  3.249197e-01
19   3.255682e-01  0.945519  3.443276e-01
20   3.420201e-01  0.939693  3.639702e-01
21   3.583679e-01  0.933580  3.838640e-01
22   3.746066e-01  0.927184  4.040262e-01
23   3.907311e-01  0.920505  4.244748e-01
24   4.067366e-01  0.913545  4.452287e-01
25   4.226183e-01  0.906308  4.663077e-01
26   4.383711e-01  0.898794  4.877326e-01
27   4.539905e-01  0.891007  5.095254e-01
28   4.694716e-01  0.882948  5.317094e-01
29   4.848096e-01  0.874620  5.543091e-01
..            ...       ...           ...
331 -4.848096e-01  0.874620 -5.543091e-01
332 -4.694716e-01  0.882948 -5.317094e-01
333 -4.539905e-01  0.891007 -5.095254e-01
334 -4.383711e-01  0.898794 -4.877326e-01
335 -4.226183e-01  0.906308 -4.663077e-01
336 -4.067366e-01  0.913545 -4.452287e-01
337 -3.907311e-01  0.920505 -4.244748e-01
338 -3.746066e-01  0.927184 -4.040262e-01
339 -3.583679e-01  0.933580 -3.838640e-01
340 -3.420201e-01  0.939693 -3.639702e-01
341 -3.255682e-01  0.945519 -3.443276e-01
342 -3.090170e-01  0.951057 -3.249197e-01
343 -2.923717e-01  0.956305 -3.057307e-01
344 -2.756374e-01  0.961262 -2.867454e-01
345 -2.588190e-01  0.965926 -2.679492e-01
346 -2.419219e-01  0.970296 -2.493280e-01
347 -2.249511e-01  0.974370 -2.308682e-01
348 -2.079117e-01  0.978148 -2.125566e-01
349 -1.908090e-01  0.981627 -1.943803e-01
350 -1.736482e-01  0.984808 -1.763270e-01
351 -1.564345e-01  0.987688 -1.583844e-01
352 -1.391731e-01  0.990268 -1.405408e-01
353 -1.218693e-01  0.992546 -1.227846e-01
354 -1.045285e-01  0.994522 -1.051042e-01
355 -8.715574e-02  0.996195 -8.748866e-02
356 -6.975647e-02  0.997564 -6.992681e-02
357 -5.233596e-02  0.998630 -5.240778e-02
358 -3.489950e-02  0.999391 -3.492077e-02
359 -1.745241e-02  0.999848 -1.745506e-02
360 -2.449294e-16  1.000000 -2.449294e-16

[361 rows x 3 columns]

In [75]:
df['fuel-type']=='gas'
df[df['fuel-type']=='gas']

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.00,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.00,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.00,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.4,8.50,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.50,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.50,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.30,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.4,7.00,160,5500,16,22,?
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.5,2.8,8.80,101,5800,23,29,16430
11,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.5,2.8,8.80,101,5800,23,29,16925
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.00,121,4250,21,28,20970
13,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.00,121,4250,21,28,21105
14,1,?,bmw,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.00,121,4250,20,25,24565
15,0,?,bmw,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.00,182,5400,16,22,30760
16,0,?,bmw,gas,std,two,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.00,182,5400,16,22,41315
17,0,?,bmw,gas,std,four,sedan,rwd,front,110.0,...,209,mpfi,3.62,3.39,8.00,182,5400,15,20,36880
18,2,121,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,61,2bbl,2.91,3.03,9.50,48,5100,47,53,5151
19,1,98,chevrolet,gas,std,two,hatchback,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70,5400,38,43,6295
20,0,81,chevrolet,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70,5400,38,43,6575
21,1,118,dodge,gas,std,two,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.41,68,5500,37,41,5572
22,1,118,dodge,gas,std,two,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68,5500,31,38,6377
23,1,118,dodge,gas,turbo,two,hatchback,fwd,front,93.7,...,98,mpfi,3.03,3.39,7.60,102,5500,24,30,7957
24,1,148,dodge,gas,std,four,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68,5500,31,38,6229
25,1,148,dodge,gas,std,four,sedan,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68,5500,31,38,6692
26,1,148,dodge,gas,std,four,sedan,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68,5500,31,38,7609
27,1,148,dodge,gas,turbo,?,sedan,fwd,front,93.7,...,98,mpfi,3.03,3.39,7.60,102,5500,24,30,8558
28,-1,110,dodge,gas,std,four,wagon,fwd,front,103.3,...,122,2bbl,3.34,3.46,8.50,88,5000,24,30,8921
29,3,145,dodge,gas,turbo,two,hatchback,fwd,front,95.9,...,156,mfi,3.6,3.9,7.00,145,5000,19,24,12964
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,2,134,toyota,gas,std,two,hatchback,rwd,front,98.4,...,146,mpfi,3.62,3.5,9.30,116,4800,24,30,9989
170,2,134,toyota,gas,std,two,hardtop,rwd,front,98.4,...,146,mpfi,3.62,3.5,9.30,116,4800,24,30,11199
171,2,134,toyota,gas,std,two,hatchback,rwd,front,98.4,...,146,mpfi,3.62,3.5,9.30,116,4800,24,30,11549
172,2,134,toyota,gas,std,two,convertible,rwd,front,98.4,...,146,mpfi,3.62,3.5,9.30,116,4800,24,30,17669
173,-1,65,toyota,gas,std,four,sedan,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.70,92,4200,29,34,8948
175,-1,65,toyota,gas,std,four,hatchback,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.70,92,4200,27,32,9988
176,-1,65,toyota,gas,std,four,sedan,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.70,92,4200,27,32,10898
177,-1,65,toyota,gas,std,four,hatchback,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.70,92,4200,27,32,11248
178,3,197,toyota,gas,std,two,hatchback,rwd,front,102.9,...,171,mpfi,3.27,3.35,9.30,161,5200,20,24,16558
179,3,197,toyota,gas,std,two,hatchback,rwd,front,102.9,...,171,mpfi,3.27,3.35,9.30,161,5200,19,24,15998
180,-1,90,toyota,gas,std,four,sedan,rwd,front,104.5,...,171,mpfi,3.27,3.35,9.20,156,5200,20,24,15690
181,-1,?,toyota,gas,std,four,wagon,rwd,front,104.5,...,161,mpfi,3.27,3.35,9.20,156,5200,19,24,15750
183,2,122,volkswagen,gas,std,two,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.4,9.00,85,5250,27,34,7975
185,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.4,9.00,85,5250,27,34,8195
186,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.4,9.00,85,5250,27,34,8495
188,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.4,10.00,100,5500,26,32,9995
189,3,?,volkswagen,gas,std,two,convertible,fwd,front,94.5,...,109,mpfi,3.19,3.4,8.50,90,5500,24,29,11595
190,3,256,volkswagen,gas,std,two,hatchback,fwd,front,94.5,...,109,mpfi,3.19,3.4,8.50,90,5500,24,29,9980
191,0,?,volkswagen,gas,std,four,sedan,fwd,front,100.4,...,136,mpfi,3.19,3.4,8.50,110,5500,19,24,13295
193,0,?,volkswagen,gas,std,four,wagon,fwd,front,100.4,...,109,mpfi,3.19,3.4,9.00,88,5500,25,31,12290
194,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.50,114,5400,23,28,12940
195,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.50,114,5400,23,28,13415
196,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.50,114,5400,24,28,15985
197,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.50,114,5400,24,28,16515
198,-2,103,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.50,162,5100,17,22,18420
199,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.50,162,5100,17,22,18950
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.50,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.70,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.80,134,5500,18,23,21485
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.50,114,5400,19,25,22625

In [79]:
len(df[df['make']=='audi'])

7

In [80]:
len(df[df['make']=='alfa-romero'])

3

In [82]:
len(df[df['make']=='bmw'])

8

In [84]:
df['make'].unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'mercedes-benz', 'mercury',
       'mitsubishi', 'nissan', 'peugot', 'plymouth', 'porsche', 'renault',
       'saab', 'subaru', 'toyota', 'volkswagen', 'volvo'], dtype=object)

In [85]:
len(df['make'].unique())

22

In [104]:
make=df['make'].unique()
count=[]
for i in make:
    print(i)
    print(len(df[df['make']==i]))
    count.append(len(df[df['make']==i]))

alfa-romero
3
audi
7
bmw
8
chevrolet
3
dodge
9
honda
13
isuzu
4
jaguar
3
mazda
17
mercedes-benz
8
mercury
1
mitsubishi
13
nissan
18
peugot
11
plymouth
7
porsche
5
renault
2
saab
6
subaru
12
toyota
32
volkswagen
12
volvo
11

In [110]:
co=[]
for i,car in enumerate(df['make'].unique()):
    y=df['make'][df['make']==car].count()
    co.append(y)
    
pd.DataFrame({'cars':df['make'].unique(), 'count':co})

             cars  count
0     alfa-romero      3
1            audi      7
2             bmw      8
3       chevrolet      3
4           dodge      9
5           honda     13
6           isuzu      4
7          jaguar      3
8           mazda     17
9   mercedes-benz      8
10        mercury      1
11     mitsubishi     13
12         nissan     18
13         peugot     11
14       plymouth      7
15        porsche      5
16        renault      2
17           saab      6
18         subaru     12
19         toyota     32
20     volkswagen     12
21          volvo     11

In [111]:
# 130 141 90

In [143]:
data=(df['engine-size']==130) | (df['engine-size']==141) | (df['engine-size']==90)

In [146]:
df['make'][data]

0      alfa-romero
1      alfa-romero
19       chevrolet
20       chevrolet
21           dodge
22           dodge
24           dodge
25           dodge
26           dodge
44           isuzu
45           isuzu
118       plymouth
120       plymouth
121       plymouth
194          volvo
195          volvo
196          volvo
197          volvo
198          volvo
199          volvo
200          volvo
201          volvo
204          volvo
Name: make, dtype: object

In [150]:
data2 = (df['engine-location']=='front') & (df['make']=='audi')

In [153]:
len(df[data2])

7